version: '3'
services:
  prometheus:
    image: prom/prometheus:v3.7.0
    container_name: klochek_m_e-netology-prometheus
    command: --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml
    ports:
    - 9090:9090
    volumes:
    - ./prometheus:/etc/prometheus
    - prometheus-data:/prometheus
    networks:
    - klochek_m_e-my-netology-hw

volumes: 
  prometheus-data:

networks:
  klochek_m_e-my-netology-hw:
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
